from collections.abc import Iterator

import ollama

from retriever import RetrievedChunk

GENERATION_MODEL = "llama3.2"

FALLBACK_RESPONSE = "I could not find this in the provided documents."


def build_prompt(question: str, chunks: list[RetrievedChunk]) -> str:
	"""Build the user prompt containing only retrieved context and the question."""
	context = "\n\n".join(
		f"Source: {chunk.source}\n{chunk.text}" for chunk in chunks
	)
	return f"""Retrieved school-document context:
{context}

Question: {question}
Answer directly from the retrieved context:"""


def stream_answer(
	question: str,
	chunks: list[RetrievedChunk],
	model: str = GENERATION_MODEL,
) -> Iterator[str]:
	"""Stream answer tokens generated by the local Ollama model."""
	if not question.strip():
		raise ValueError("question must not be blank")
	if not chunks:
		yield FALLBACK_RESPONSE
		return

	try:
		stream = ollama.chat(
			model=model,
			messages=[
				{
					"role": "system",
					"content": (
						"Answer only from the provided school-document context. "
						"For broad questions, summarize relevant context immediately; "
						"never ask the user to provide a more specific question. "
						"If the context has no relevant information, reply exactly: "
						"I could not find this in the provided documents. "
						"Do not repeat these instructions or append the fallback after answering."
					),
				},
				{"role": "user", "content": build_prompt(question, chunks)},
			],
			options={"temperature": 0},
			stream=True,
		)
		for chunk in stream:
			token = chunk.get("message", {}).get("content", "")
			if token:
				yield token
	except Exception as error:
		raise RuntimeError(
			f"Unable to generate an answer. Is Ollama running with '{model}' pulled? "
			f"Original error: {error}"
		) from error


def generate_answer(
	question: str,
	chunks: list[RetrievedChunk],
	model: str = GENERATION_MODEL,
) -> str:
	"""Generate a grounded answer with the local Ollama model (non-streaming)."""
	content = "".join(stream_answer(question, chunks, model=model)).strip()
	if not content:
		raise RuntimeError("The language model returned an empty answer")
	return content
